### ISSUE TITLE
Test multiple device types

### ISSUE THREAD

**Issue by zachgharst** [pkiuna/Web-Development-2--Simply-CDL#10]

**Comment by Bobbyjuba** [comment]
Tested using Edge's device emulation tool in the inspector (CTRL+SHIFT+I). On desktop, tablets, and the responsive setting, the pages all scaled appropriately and correctly. On phones, the pages looked very clean, but the menu toolbar was a bit smushed together. I verified this using my iPhone, it appeared the same as the emulation tool. The content looks fine, just the toolbar at the top appears smushed. Otherwise, everything else looks acceptable.
